(() => {
  const canvas = document.querySelector('#game'), ctx = canvas.getContext('2d');
  const paintedSky=new Image();paintedSky.src='assets/battle-sky.webp';
  const wormSprite=new Image();wormSprite.src='assets/worm-soldier.webp';
  const firebaseConfig={apiKey:'AIzaSyBBUSX_w2v_X91GDH2dYJFJueDAxzuyFiw',authDomain:'game-8cc37.firebaseapp.com',databaseURL:'https://game-8cc37-default-rtdb.europe-west1.firebasedatabase.app',projectId:'game-8cc37',storageBucket:'game-8cc37.firebasestorage.app',messagingSenderId:'590593619384',appId:'1:590593619384:web:3d7dbda59a32dab7dfcb4d'};
  let gameStarted=false, selectedPlayer=null, lobbyRef=null, isHost=false, networkBound=false, lastStatePublish=0, lastAimPublish=0;
  const terrain = document.createElement('canvas'), tctx = terrain.getContext('2d');
  terrain.width = canvas.width; terrain.height = canvas.height;
  const W = canvas.width, H = canvas.height, R = 17, WATER = 625;
  let terrainPixels;
  let worms, active, projectile, gameOver, turnStart, last, mouse = { x: 900, y: 280 }, charging = false, chargeStart = 0, explosions = [], graves = [], particles = [], weapon = 'bazooka', weaponMenu = false, menuPos = {x:0,y:0}, airstrike = null, airBombs = [], airstrikeDone=false, goatDrop=null, mineDrop=null, reinforceDrop=null, mines=[], levelSeed = 0, goats = [], birds=[], botMode=false, botThink=0, botMove=0, botDir=1, botJump=false, botAction=false, botWallMode=false, wallUses=3, turnPending=false, lastTurnAt=0, shotId=0;
  const keys = {};
  const teams = [{ name: 'Красные', color: '#ef5a4b', dark: '#b83c3a' }, { name: 'Синие', color: '#4e93e5', dark: '#2769b5' }];
  const names=['Петя','Вася','Федя','Гриша','Боря','Кузя','Семён','Толик','Жора','Митя'];

  function reset() {
    levelSeed = Math.random()*10000;
    tctx.clearRect(0, 0, W, H);
    const land = tctx.createLinearGradient(0, 360, 0, H); land.addColorStop(0, '#78b851'); land.addColorStop(.04, '#48863f'); land.addColorStop(1, '#294d32');
    // Smooth random terrain, with broad enough ledges for every spawn point.
    const anchors=[{x:0,y:440}], spawnXs=[150,355,880,1120];
    for(let x=80;x<W;x+=80) anchors.push({x,y:Math.max(325,Math.min(500,410+(Math.random()-.5)*150))});
    anchors.push({x:W,y:400}); spawnXs.forEach(sx=>{let near=anchors.reduce((best,p)=>Math.abs(p.x-sx)<Math.abs(best.x-sx)?p:best);near.y=Math.max(355,Math.min(460,near.y));});
    tctx.fillStyle = land; tctx.beginPath();tctx.moveTo(0,anchors[0].y);anchors.forEach((p,i)=>{if(i){let prev=anchors[i-1],mid=(prev.x+p.x)/2;tctx.quadraticCurveTo(prev.x,prev.y,mid,(prev.y+p.y)/2);}});tctx.lineTo(W,anchors.at(-1).y);tctx.lineTo(W,WATER);tctx.lineTo(0,WATER);tctx.closePath();tctx.fill();
    // A few random floating islands give each round a different route.
    const islands=2+Math.floor(Math.random()*3);for(let i=0;i<islands;i++){let x=150+Math.random()*(W-300), y=185+Math.random()*145, w=90+Math.random()*105;tctx.beginPath();tctx.ellipse(x,y,w/2,18+Math.random()*10,0,0,Math.PI*2);tctx.fill();}refreshTerrain();
    const picked=[...names].sort(()=>Math.random()-.5);worms = spawnXs.map((x,i)=>mk(i<2?0:1,x,groundY(x),picked[i]));
    goats=[]; for(let i=0;i<4+Math.floor(Math.random()*3);i++){let x=80+Math.random()*(W-160);goats.push({x,y:groundY(x)-2,vx:(Math.random()>.5?1:-1)*(18+Math.random()*18),vy:0,face:Math.random()>.5?1:-1,hp:45,alive:true,think:1+Math.random()*3,bleat:2+Math.random()*5,bubble:0,ground:false});}
    birds=Array.from({length:3},(_,i)=>({x:Math.random()*W,y:105+Math.random()*190,vx:30+Math.random()*28,phase:i*2,alive:true}));mines=[];mineDrop=null;reinforceDrop=null;active = 0; projectile = null; gameOver = false; graves = []; explosions = []; particles = [];airBombs=[];airstrikeDone=false; charging = false; weapon = 'bazooka'; weaponMenu = false; airstrike = null; botThink=0;botMove=0;botJump=false;botAction=false;botWallMode=false;wallUses=3;turnPending=false;lastTurnAt=0;document.querySelector('#gameOverMenu').style.display='none'; turnStart = performance.now();
  }
  function mk(team,x,y,name) { return { team,x,y,name,weapon:'bazooka',vx:0,vy:0,hp:100,alive:true,face: team? -1:1,ground:false,flash:0 }; }
  function groundY(x) { for(let y=100;y<WATER;y++) if(solid(x,y)) return y-R-1; return WATER-R-1; }
  function refreshTerrain() { terrainPixels=tctx.getImageData(0,0,W,H).data;if(isHost&&gameStarted)queueMicrotask(publishTerrain); }
  function solid(x,y) { x|=0;y|=0;return x < 1 || x >= W-1 || (y >= 0 && y < WATER && terrainPixels[(y*W+x)*4+3] > 0); }
  function circleHits(x,y,r=R) { for(let a=0;a<Math.PI*2;a+=Math.PI/12) if(solid(x+Math.cos(a)*r,y+Math.sin(a)*r)) return true; return false; }
  function activeWorm() { return worms[active]; }
  function ownsTurn() { const w=activeWorm();return gameStarted&&w&&selectedPlayer&&w.team===Number(selectedPlayer)-1; }
  function serializableState() { return {worms,active,projectile,gameOver,goats,graves,mines,birds,airBombs,airstrike,airstrikeDone,goatDrop,mineDrop,reinforceDrop,explosions,particles,wallUses,remain:Math.max(0,30-(performance.now()-turnStart)/1000),mouse}; }
  function publishTerrain() { if(isHost&&gameStarted&&lobbyRef) lobbyRef.child('terrain').set(terrain.toDataURL('image/webp',.72)); }
  function publishState(force=false) { if(!isHost||!gameStarted||!lobbyRef)return;let now=performance.now();if(!force&&now-lastStatePublish<90)return;lastStatePublish=now;lobbyRef.child('state').set(serializableState()); }
  function applyRemoteState(s) { if(!s||isHost)return;worms=s.worms||worms;active=s.active??active;projectile=s.projectile||null;gameOver=!!s.gameOver;goats=s.goats||[];graves=s.graves||[];mines=s.mines||[];birds=s.birds||[];airBombs=s.airBombs||[];airstrike=s.airstrike||null;airstrikeDone=!!s.airstrikeDone;goatDrop=s.goatDrop||null;mineDrop=s.mineDrop||null;reinforceDrop=s.reinforceDrop||null;explosions=s.explosions||[];particles=s.particles||[];wallUses=s.wallUses??wallUses;if(s.mouse)mouse=s.mouse;turnStart=performance.now()-(30-(s.remain??30))*1000; }
  function sendCommand(type,payload={}) { if(!lobbyRef||!selectedPlayer)return;lobbyRef.child('commands').push({type,payload,player:selectedPlayer,at:firebase.database.ServerValue.TIMESTAMP}); }
  function applyCommand(c) { if(!c||!isHost)return;const w=activeWorm();if(!w||w.team!==Number(c.player)-1)return;if(c.type==='aim'){mouse=c.payload;}else if(c.type==='weapon'){w.weapon=c.payload.weapon;weapon=w.weapon;}else if(c.type==='fire'){mouse=c.payload.mouse;fire(c.payload.power??1);} }
  function bindNetwork() { if(networkBound)return;networkBound=true;if(isHost){lobbyRef.child('commands').limitToLast(1).on('child_added',snap=>{const c=snap.val();if(c&&c.player!=='1')applyCommand(c);snap.ref.remove();});lobbyRef.child('input/2').on('value',snap=>{const v=snap.val()||{};['KeyA','KeyD','ArrowLeft','ArrowRight','KeyW','ArrowUp'].forEach(k=>keys[k]=!!v[k]);});publishTerrain();publishState(true);}else{lobbyRef.child('state').on('value',snap=>applyRemoteState(snap.val()));lobbyRef.child('terrain').on('value',snap=>{const src=snap.val();if(!src)return;const img=new Image();img.onload=()=>{tctx.clearRect(0,0,W,H);tctx.drawImage(img,0,0);refreshTerrain();};img.src=src;});} }
  function queueNextTurn(delay){if(turnPending||gameOver)return;turnPending=true;setTimeout(()=>{turnPending=false;nextTurn();},delay);}
  function nextTurn() { const now=performance.now();if(gameOver||now-lastTurnAt<350) return;lastTurnAt=now; let aliveTeams = teams.map((_,t)=>worms.some(w=>w.alive&&w.team===t)); if(!aliveTeams[0]||!aliveTeams[1]) { gameOver = true; return; } do { active=(active+1)%worms.length; } while(!worms[active].alive);const w=activeWorm();botThink=botMode&&w.team===1?1.1+Math.random()*1.1:0;botMove=botMode&&w.team===1?.35+Math.random()*.8:0;botDir=Math.random()>.5?1:-1;botJump=Math.random()>.42;botAction=false;botWallMode=false;wallUses=3;turnStart=now; }
  function newName(){const used=new Set(worms.map(w=>w.name));return names.find(n=>!used.has(n))||`Боец ${worms.length+1}`;}
  function fire(power = 1) { const w=activeWorm(); if(!w || projectile || gameOver || weaponMenu || airstrike || airBombs.length || airstrikeDone || goatDrop || mineDrop || reinforceDrop) return; weapon=w.weapon;if(weapon==='airstrike'){ airstrike={x:mouse.x,delay:.15,count:0}; return; } if(weapon==='goatdrop'){goatDrop={x:-90,target:mouse.x,delay:.35,count:0};return;}if(weapon==='minedrop'){mineDrop={x:-90,target:mouse.x,delay:.25,count:0};return;}if(weapon==='reinforce'){reinforceDrop={x:-90,target:mouse.x,delay:.3,count:0};return;} if(weapon==='wall'){if(!wallUses)return;placeWall(mouse.x,mouse.y);wallUses--;if(!wallUses)queueNextTurn(300);return;} const dx=mouse.x-w.x, dy=mouse.y-(w.y-5), len=Math.hypot(dx,dy)||1, speed=230+power*430,shot=++shotId; projectile={x:w.x+dx/len*26,y:w.y-5+dy/len*26,vx:dx/len*speed,vy:dy/len*speed,age:0};setTimeout(()=>{if(shot===shotId&&activeWorm()===w){projectile=null;queueNextTurn(0);}},6000); }
  function placeWall(x,y){x=Math.max(52,Math.min(W-52,x));y=Math.max(8,Math.min(WATER-8,y));tctx.fillStyle='#647178';tctx.fillRect(x-52,y-7,104,14);tctx.strokeStyle='#d5624b';tctx.lineWidth=2;for(let xx=x-47;xx<x+48;xx+=13){tctx.beginPath();tctx.moveTo(xx,y-6);tctx.lineTo(xx+8,y+6);tctx.stroke();}refreshTerrain();}
  function kill(w) { if(!w.alive) return; w.alive=false; graves.push({x:w.x,y:Math.min(w.y,WATER-28),vx:w.vx*.45,vy:Math.min(w.vy,-40),tilt:(Math.random()-.5)*.16,spin:(Math.random()-.5)*2,ground:false}); if(w===activeWorm()) queueNextTurn(350); }
  function explode(p, ending=true) { const rad=58; explosions.push({x:p.x,y:p.y,age:0,max:.52});
    // Several overlapping bites make a ragged, more natural crater edge.
    tctx.save(); tctx.globalCompositeOperation='destination-out'; for(let n=0;n<10;n++){let a=Math.random()*Math.PI*2,d=Math.random()*rad*.28,r=rad*(.68+Math.random()*.35);tctx.beginPath();tctx.arc(p.x+Math.cos(a)*d,p.y+Math.sin(a)*d,r,0,7);tctx.fill();} tctx.restore();refreshTerrain();
    for(let n=0;n<48;n++){let a=Math.random()*Math.PI*2,s=70+Math.random()*330;particles.push({x:p.x,y:p.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-80,life:.55+Math.random()*.45,size:2+Math.random()*5,color:Math.random()>.45?'#77583d':'#e8bd70'});}
    worms.forEach(w=>{if(!w.alive)return;let d=Math.hypot(w.x-p.x,w.y-p.y);if(d<rad+35){let dmg=Math.round(Math.max(0,100-d*1.25));w.hp=Math.max(0,w.hp-dmg);w.flash=.45;if(!w.hp)kill(w);let f=Math.max(0,1-d/(rad+35));w.vx+=(w.x-p.x)/(d||1)*310*f;w.vy+=(w.y-p.y)/(d||1)*310*f;}}); goats.forEach(g=>{if(!g.alive)return;let d=Math.hypot(g.x-p.x,g.y-p.y);if(d<rad+27){g.hp-=Math.round(Math.max(0,80-d));let f=Math.max(0,1-d/(rad+27));g.vx+=(g.x-p.x)/(d||1)*380*f;g.vy+=(g.y-p.y)/(d||1)*310*f;if(g.hp<=0)g.alive=false;}});birds.forEach(b=>{if(Math.hypot(b.x-p.x,b.y-p.y)<rad+14)b.alive=false;});mines.forEach(m=>{let d=Math.hypot(m.x-p.x,m.y-p.y),f=Math.max(0,1-d/(rad+45));if(f){m.vx+=(m.x-p.x)/(d||1)*360*f;m.vy+=(m.y-p.y)/(d||1)*360*f;}}); projectile=null; if(ending)setTimeout(nextTurn,520); }
  function update(dt) {
    if(!gameStarted) return;
    if(!isHost) return;
    if(!gameOver && !projectile && performance.now()-turnStart>30000) nextTurn();
    if(botMode&&!gameOver&&!botAction&&activeWorm()?.team===1&&!projectile&&!airstrike&&!airBombs.length&&!goatDrop&&!mineDrop&&!reinforceDrop){
      if(botThink>0)botThink-=dt;
      else if(botMove>0)botMove-=dt;
      else {const targets=worms.filter(w=>w.alive&&w.team===0),target=targets[Math.floor(Math.random()*targets.length)];if(target){const botWeapon=botWallMode?'wall':['bazooka','airstrike','wall','goatdrop','minedrop','reinforce'][Math.floor(Math.random()*6)];if(botWeapon==='wall')botWallMode=true;mouse=botWeapon==='wall'?{x:Math.max(60,Math.min(W-60,activeWorm().x+botDir*(75+(3-wallUses)*125))),y:Math.max(90,Math.min(WATER-20,activeWorm().y+8))}:{x:Math.max(30,Math.min(W-30,target.x+(Math.random()-.5)*90)),y:Math.max(45,target.y-10+(Math.random()-.5)*55)};activeWorm().weapon=botWeapon;weapon=botWeapon;botAction=true;fire(.45+Math.random()*.35);if(botWeapon==='wall'&&wallUses){botAction=false;botThink=.22;}}}
    }
    worms.forEach((w,i)=>{ if(!w.alive)return; if(i===active&&!projectile&&!gameOver){w.face=mouse.x>=w.x?1:-1;if(botMode&&w.team===1){if(botThink<=0&&botMove>0){w.vx+=botDir*850*dt;w.face=botDir;if(botJump&&w.ground){w.vy=-385;w.ground=false;botJump=false;}}}else { if(keys.KeyA||keys.ArrowLeft){w.vx-=850*dt;w.face=-1;} if(keys.KeyD||keys.ArrowRight){w.vx+=850*dt;w.face=1;} if(keys.Space&&w.ground){w.vy=-385;w.ground=false;keys.Space=false;} }} w.vx*=Math.pow(.0002,dt); w.vx=Math.max(-135,Math.min(135,w.vx)); w.vy+=780*dt;
      // When meeting a crater edge, search up to a small "step" height before stopping.
      let mx=w.vx*dt, steps=Math.ceil(Math.abs(mx)/2)||1, sx=mx/steps; for(let n=0;n<steps;n++){
        if(!circleHits(w.x+sx,w.y)) { w.x+=sx; continue; }
        let stepped=false;
        if(w.ground) for(let rise=3;rise<=14;rise+=3) if(!circleHits(w.x+sx,w.y-rise)) { w.x+=sx; w.y-=rise; stepped=true; break; }
        if(!stepped) { w.vx=0; break; }
      }
      let my=w.vy*dt, vsteps=Math.ceil(Math.abs(my)/2)||1, sy=my/vsteps; w.ground=false; for(let n=0;n<vsteps;n++){if(!circleHits(w.x,w.y+sy))w.y+=sy;else {if(sy>0)w.ground=true;w.vy=0;break;}} if(w.y+R>=WATER) kill(w); w.flash=Math.max(0,w.flash-dt); });
    goats.forEach(g=>{if(!g.alive)return;g.think-=dt;g.bleat-=dt;g.bubble=Math.max(0,g.bubble-dt);if(g.bleat<=0){g.bubble=1.2;g.bleat=3+Math.random()*6;}if(g.think<=0){g.face=Math.random()>.5?1:-1;g.vx=g.face*(22+Math.random()*32);g.think=1+Math.random()*3;}g.vy+=g.parachute?125*dt:780*dt;let nx=g.x+g.vx*dt;if(!circleHits(nx,g.y,10))g.x=nx;else{let stepped=false;for(let rise=3;rise<=12;rise+=3)if(!circleHits(nx,g.y-rise,10)){g.x=nx;g.y-=rise;stepped=true;break;}if(!stepped){g.face*=-1;g.vx=g.face*(18+Math.random()*20);g.think=.8+Math.random()*2;}}let ny=g.y+g.vy*dt;g.ground=false;if(!circleHits(g.x,ny,10))g.y=ny;else{if(g.vy>0)g.ground=true;g.vy=0;g.parachute=false;}if(g.y+10>=WATER)g.alive=false;});
    graves.forEach(g=>{ g.vy+=780*dt; g.vx*=Math.pow(.03,dt); g.tilt+=g.spin*dt; let nx=g.x+g.vx*dt; if(!solid(nx,g.y+12)) g.x=nx; else { g.vx*=-.15; g.spin*=.5; } let ny=g.y+g.vy*dt; g.ground=false; if(!solid(g.x,ny+12)) g.y=ny; else { if(g.vy>0) g.ground=true; g.vy=0; g.spin*=.35; } });graves=graves.filter(g=>g.y<H+45);
    particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=670*dt;p.vx*=Math.pow(.08,dt);p.life-=dt;}); particles=particles.filter(p=>p.life>0&&p.y<WATER+10);
    birds.forEach(b=>{if(b.alive){b.x+=b.vx*dt;if(b.x>W+30)b.x=-30;}});
    if(airstrike){airstrike.delay-=dt;if(airstrike.delay<=0){let x=airstrike.x+(Math.random()-.5)*105;airBombs.push({x,y:-20,vx:(Math.random()-.5)*35,vy:150,age:0});airstrike.count++;airstrike.delay=.22;if(airstrike.count>=3){airstrike=null;airstrikeDone=true;}}}
    if(goatDrop){goatDrop.x+=420*dt;goatDrop.delay-=dt;if(goatDrop.x>goatDrop.target-110&&goatDrop.x<goatDrop.target+110&&goatDrop.delay<=0&&goatDrop.count<5){let x=goatDrop.x+(Math.random()-.5)*28;goats.push({x,y:40,vx:(Math.random()-.5)*20,vy:30,face:1,hp:45,alive:true,think:1,bleat:2,bubble:0,parachute:true,ground:false});goatDrop.count++;goatDrop.delay=.25;}if(goatDrop.x>W+100){goatDrop=null;queueNextTurn(350);}}
    if(mineDrop){mineDrop.x+=420*dt;mineDrop.delay-=dt;if(mineDrop.x>mineDrop.target-95&&mineDrop.x<mineDrop.target+95&&mineDrop.delay<=0&&mineDrop.count<6){mines.push({x:mineDrop.x,y:58,vx:(Math.random()-.5)*60,vy:20,armed:.7});mineDrop.count++;mineDrop.delay=.2;}if(mineDrop.x>W+100){mineDrop=null;queueNextTurn(350);}}
    if(reinforceDrop){reinforceDrop.x+=420*dt;reinforceDrop.delay-=dt;if(reinforceDrop.x>reinforceDrop.target-55&&reinforceDrop.x<reinforceDrop.target+55&&reinforceDrop.delay<=0&&reinforceDrop.count<2){const team=reinforceDrop.count,offset=team?32:-32;worms.push(mk(team,Math.max(35,Math.min(W-35,reinforceDrop.x+offset)),45,newName()));reinforceDrop.count++;reinforceDrop.delay=.35;}if(reinforceDrop.x>W+100){reinforceDrop=null;queueNextTurn(350);}}
    mines.forEach(m=>{m.armed-=dt;m.vy+=760*dt;let nx=m.x+m.vx*dt;if(!solid(nx,m.y))m.x=nx;else m.vx*=-.42;let ny=m.y+m.vy*dt;if(!solid(m.x,ny+8))m.y=ny;else {m.y-=2;m.vy*=-.32;m.vx*=.72;}if(m.y>WATER)m.dead=true;if(m.armed<=0){let target=worms.some(w=>w.alive&&Math.hypot(w.x-m.x,w.y-m.y)<35)||goats.some(g=>g.alive&&Math.hypot(g.x-m.x,g.y-m.y)<29)||birds.some(b=>b.alive&&Math.hypot(b.x-m.x,b.y-m.y)<25);if(target){m.dead=true;explode(m,false);}}});mines=mines.filter(m=>!m.dead);
    if(projectile){let p=projectile;p.age+=dt;p.vy+=(p.air?350:620)*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<0||p.x>W||p.y>H||solid(p.x,p.y)||p.age>5)explode(p,!p.air||(!airstrike&&airstrike!==null));}
    airBombs.forEach(p=>{p.age+=dt;p.vy+=410*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<0||p.x>W||p.y>H||solid(p.x,p.y)||p.age>5){p.dead=true;explode(p,false);}});airBombs=airBombs.filter(p=>!p.dead);if(airstrikeDone&&!airBombs.length){airstrikeDone=false;queueNextTurn(450);}publishState();
  }
  function text(s,x,y,size,fill='#fff') { ctx.font=`900 ${size}px Nunito, sans-serif`;ctx.textAlign='center';ctx.fillStyle=fill;ctx.fillText(s,x,y); }
  function drawSky() { const t=performance.now()/1000,g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#62b7e2');g.addColorStop(1,'#c9e5b8');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);if(paintedSky.complete)ctx.drawImage(paintedSky,0,0,W,430);ctx.fillStyle='#ffe89b';ctx.globalAlpha=.85;ctx.beginPath();ctx.arc(1080,92+Math.sin(t*.7)*3,36,0,7);ctx.fill();ctx.globalAlpha=.25;ctx.fillStyle='#fff';[[130,96,68],[460,70,47],[900,100,82],[1130,58,45]].forEach(([x,y,s],i)=>{x=((x+t*(7+i*2))%(W+170))-85;ctx.beginPath();ctx.arc(x,y,s*.36,0,7);ctx.arc(x+s*.35,y+4,s*.28,0,7);ctx.arc(x-s*.35,y+8,s*.25,0,7);ctx.fill();});ctx.globalAlpha=1; }
  function drawWater() { const t=performance.now()/1000;ctx.fillStyle='#197eae';ctx.fillRect(0,WATER,W,H-WATER);for(let row=0;row<4;row++){ctx.strokeStyle=`rgba(136,236,246,${.42-row*.07})`;ctx.lineWidth=2;ctx.beginPath();for(let x=0;x<=W;x+=9){let y=WATER+6+row*21+Math.sin(x*.036+t*(2.8+row*.3)+row)*3; x?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();} }
  function drawGrave(g) { ctx.save();ctx.translate(g.x,g.y);ctx.rotate(g.tilt);ctx.fillStyle='#4b554f55';ctx.beginPath();ctx.ellipse(0,4,15,4,0,0,7);ctx.fill();ctx.fillStyle='#85878a';ctx.fillRect(-10,-28,20,28);ctx.beginPath();ctx.arc(0,-28,10,Math.PI,0);ctx.fill();ctx.strokeStyle='#3c464c';ctx.lineWidth=2;ctx.strokeRect(-10,-28,20,28);text('✝',0,-9,15,'#e6e1ca');ctx.restore(); }
  function drawGoat(g) { if(!g.alive)return;let t=performance.now()/1000, step=Math.sin(t*10+g.x*.1)*2;if(g.parachute){ctx.strokeStyle='#e6e9e8';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(g.x-9,g.y-5);ctx.lineTo(g.x-16,g.y-28);ctx.moveTo(g.x+9,g.y-5);ctx.lineTo(g.x+16,g.y-28);ctx.stroke();ctx.fillStyle='#e55e57';ctx.beginPath();ctx.arc(g.x,g.y-31,17,Math.PI,0);ctx.lineTo(g.x+17,g.y-29);ctx.lineTo(g.x-17,g.y-29);ctx.fill();}ctx.save();ctx.translate(g.x,g.y);ctx.scale(g.face,1);ctx.fillStyle='#f4e5c1';ctx.beginPath();ctx.ellipse(0,0,14,9,0,0,7);ctx.fill();ctx.beginPath();ctx.arc(11,-7,7,0,7);ctx.fill();ctx.strokeStyle='#5a463a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-6,7);ctx.lineTo(-6,14+step);ctx.moveTo(6,7);ctx.lineTo(6,14-step);ctx.moveTo(13,-12);ctx.lineTo(18,-18);ctx.moveTo(10,-12);ctx.lineTo(6,-18);ctx.stroke();ctx.fillStyle='#292b30';ctx.beginPath();ctx.arc(14,-8,1.6,0,7);ctx.fill();ctx.restore();if(g.bubble){ctx.fillStyle='#fffdf4';ctx.beginPath();ctx.roundRect(g.x-18,g.y-43,42,19,8);ctx.fill();text('Беее!',g.x+3,g.y-29,10,'#4d4540');} }
  function drawExplosion(e) { let q=e.age/e.max,r=16+q*76;ctx.save();ctx.globalAlpha=1-q;ctx.strokeStyle='#fff3a1';ctx.lineWidth=5*(1-q);ctx.beginPath();ctx.arc(e.x,e.y,r*1.2,0,7);ctx.stroke();let g=ctx.createRadialGradient(e.x,e.y,1,e.x,e.y,r);g.addColorStop(0,'#fffbe0');g.addColorStop(.25,'#ffd84d');g.addColorStop(.62,'#f46b3e');g.addColorStop(1,'#8c3140');ctx.fillStyle=g;ctx.beginPath();ctx.arc(e.x,e.y,r,0,7);ctx.fill();for(let i=0;i<8;i++){let a=i*Math.PI/4+q*3;ctx.fillStyle='#ffe87a';ctx.beginPath();ctx.arc(e.x+Math.cos(a)*r*.7,e.y+Math.sin(a)*r*.7,5*(1-q),0,7);ctx.fill();}ctx.restore(); }
  function drawWeaponMenu() { let {x,y}=menuPos;ctx.fillStyle='#152437ed';ctx.fillRect(x,y,205,139);ctx.strokeStyle='#9bc8da';ctx.lineWidth=2;ctx.strokeRect(x,y,205,139);text('ОРУЖИЕ',x+102,y+22,13,'#b5dded');[['bazooka','🚀  Базука'],['airstrike','☄  Авиаудар'],['wall','▥  Арматурная стенка']].forEach(([id,label],i)=>{let yy=y+34+i*33;ctx.fillStyle=weapon===id?'#3c7698':'#22384b';ctx.fillRect(x+7,yy,191,27);ctx.textAlign='left';ctx.font='800 14px Nunito';ctx.fillStyle='#fff';ctx.fillText(label,x+17,yy+19);}); }
  function drawWeaponBar() { const w=activeWorm();if(!w)return;let x=W-225,y=15;ctx.fillStyle='#132238d9';ctx.fillRect(x,y,210,201);ctx.strokeStyle='#83c2db';ctx.lineWidth=2;ctx.strokeRect(x,y,210,201);text('ОРУЖИЕ',x+105,y+19,12,'#caedf4');[['bazooka','1  🚀  Базука'],['airstrike','2  ☄  Авиаудар'],['wall',`3  ▥  Арматура (${wallUses}/3)`],['goatdrop','4  🐐  Сброс козликов'],['minedrop','5  💣  Сброс мин'],['reinforce','6  🪂  Подкрепление']].forEach(([id,label],i)=>{let yy=y+27+i*28;ctx.fillStyle=w.weapon===id?'#e89d45':'#29455b';ctx.fillRect(x+7,yy,196,23);ctx.textAlign='left';ctx.font='800 13px Nunito';ctx.fillStyle=w.weapon===id?'#182332':'#f4fbff';ctx.fillText(label,x+14,yy+16);}); }
  function drawWallPreview() { let x=Math.max(52,Math.min(W-52,mouse.x)),y=Math.max(8,Math.min(WATER-8,mouse.y));ctx.save();ctx.fillStyle='#647178';ctx.globalAlpha=.72;ctx.fillRect(x-52,y-7,104,14);ctx.globalAlpha=1;ctx.strokeStyle='#fff3a3';ctx.lineWidth=2;ctx.strokeRect(x-52,y-7,104,14);ctx.strokeStyle='#ff7655';ctx.lineWidth=2;for(let xx=x-47;xx<x+48;xx+=13){ctx.beginPath();ctx.moveTo(xx,y-6);ctx.lineTo(xx+8,y+6);ctx.stroke();}ctx.fillStyle='#fff8d1';ctx.font='900 12px Nunito';ctx.textAlign='center';ctx.fillText(`АРМАТУРА: ${wallUses}/3`,x,y-18);ctx.restore(); }
  function drawWorm(w,i) { if(!w.alive)return; const tm=teams[w.team], moving=Math.abs(w.vx)>12, t=performance.now()/1000, bob=(moving?Math.sin(t*13)*2:Math.sin(t*2+i)*1.2);ctx.save();ctx.translate(w.x,w.y+bob); if(w.flash){ctx.globalAlpha=.5+Math.sin(w.flash*65)*.5;}ctx.fillStyle='#15213755';ctx.beginPath();ctx.ellipse(0,20,20,6,0,0,7);ctx.fill();ctx.strokeStyle=tm.dark;ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-7,14);ctx.lineTo(-10+(moving?Math.sin(t*13)*4:0),20);ctx.moveTo(7,14);ctx.lineTo(10+(moving?-Math.sin(t*13)*4:0),20);ctx.stroke();ctx.fillStyle=tm.color;ctx.beginPath();ctx.ellipse(0,0,R,R*1.05,0,0,7);ctx.fill();ctx.strokeStyle=tm.dark;ctx.lineWidth=3;ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.ellipse(w.face*5,-5,6,7,0,0,7);ctx.fill();ctx.fillStyle='#1b2634';ctx.beginPath();ctx.arc(w.face*6,-5,2.3,0,7);ctx.fill();ctx.strokeStyle='#362b35';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w.face*3,6,5,.2,2.9);ctx.stroke();ctx.restore();if(wormSprite.complete){ctx.save();ctx.translate(w.x,w.y+bob-3);ctx.scale(w.face,1);if(w.team===1)ctx.filter='hue-rotate(145deg) saturate(1.2)';ctx.drawImage(wormSprite,-31,-28,62,56);ctx.restore();}
    ctx.fillStyle='#182032cc';ctx.fillRect(w.x-24,w.y-34,48,7);ctx.fillStyle=tm.color;ctx.fillRect(w.x-22,w.y-32,44*w.hp/100,3);ctx.font='900 13px Nunito';const nw=ctx.measureText(w.name).width+14;ctx.fillStyle='#101827e8';ctx.beginPath();ctx.roundRect(w.x-nw/2,w.y-59,nw,18,7);ctx.fill();text(w.name,w.x,w.y-45,13,'#fff9de');let aim=i===active?Math.atan2(mouse.y-(w.y+3),mouse.x-w.x):0;ctx.save();ctx.translate(w.x,w.y+3);ctx.rotate(aim);if(w.weapon==='wall'){ctx.strokeStyle='#a4b4ba';ctx.lineWidth=3;ctx.strokeRect(-4,-10,22,20);ctx.beginPath();ctx.moveTo(3,-10);ctx.lineTo(3,10);ctx.moveTo(11,-10);ctx.lineTo(11,10);ctx.moveTo(-4,-3);ctx.lineTo(18,-3);ctx.moveTo(-4,4);ctx.lineTo(18,4);ctx.stroke();}else if(['airstrike','goatdrop','minedrop','reinforce'].includes(w.weapon)){ctx.fillStyle='#2b3844';ctx.fillRect(-6,-11,15,22);ctx.strokeStyle='#b7d9e2';ctx.lineWidth=2;ctx.strokeRect(-6,-11,15,22);ctx.fillStyle='#70d8d0';ctx.fillRect(-3,-7,9,6);ctx.strokeStyle='#222b35';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(1,-11);ctx.lineTo(6,-20);ctx.stroke();ctx.fillStyle='#e8c18e';ctx.beginPath();ctx.arc(8,5,4,0,7);ctx.fill();}else{ctx.fillStyle='#4d5b2b';ctx.fillRect(-2,-6,38,12);ctx.fillStyle='#1c2631';ctx.fillRect(21,-9,12,18);ctx.fillStyle='#e8c18e';ctx.beginPath();ctx.arc(5,0,4,0,7);ctx.fill();}ctx.restore();
    if(i===active&&!gameOver){ctx.strokeStyle='#fff8a7';ctx.lineWidth=3;ctx.beginPath();ctx.arc(w.x,w.y,27,0,7);ctx.stroke();}
  }
  function draw() { drawSky();ctx.drawImage(terrain,0,0);drawWater();if(goatDrop||mineDrop){let drop=goatDrop||mineDrop;ctx.save();ctx.translate(drop.x,72);ctx.fillStyle='#59667d';ctx.beginPath();ctx.moveTo(-42,0);ctx.lineTo(25,0);ctx.lineTo(43,10);ctx.lineTo(25,17);ctx.lineTo(-32,17);ctx.closePath();ctx.fill();ctx.fillStyle='#dfe9ef';ctx.fillRect(-10,17,13,6);ctx.fillStyle='#e9a95b';ctx.fillRect(8,4,13,7);ctx.restore();}birds.forEach(b=>{if(b.alive){let flap=Math.sin(performance.now()/75+b.phase)*10;ctx.save();ctx.translate(b.x,b.y);ctx.fillStyle='#f1c453';ctx.beginPath();ctx.ellipse(0,0,9,5,0,0,7);ctx.fill();ctx.fillStyle='#ed7545';ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(15,2);ctx.lineTo(8,4);ctx.fill();ctx.strokeStyle='#3d4964';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-5,0);ctx.quadraticCurveTo(-11,-flap,-17,-2);ctx.moveTo(-1,0);ctx.quadraticCurveTo(3,-flap,7,-2);ctx.stroke();ctx.fillStyle='#22293a';ctx.beginPath();ctx.arc(5,-1,1.3,0,7);ctx.fill();ctx.restore();}});graves.forEach(drawGrave);goats.forEach(drawGoat);mines.forEach(m=>{ctx.fillStyle=m.armed>0?'#313b43':'#e44942';ctx.beginPath();ctx.arc(m.x,m.y,9,0,7);ctx.fill();ctx.strokeStyle='#d8e0df';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#ffdc60';ctx.beginPath();ctx.arc(m.x,m.y,2,0,7);ctx.fill();}); worms.forEach(drawWorm); if(!projectile&&!gameOver){const w=activeWorm();weapon=w.weapon;if(w){if(w.weapon==='bazooka'){ctx.strokeStyle='#ffffffaa';ctx.setLineDash([6,7]);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(w.x,w.y-5);ctx.lineTo(mouse.x,mouse.y);ctx.stroke();ctx.setLineDash([]);}if(charging){let p=Math.min(1,(performance.now()-chargeStart)/1300);ctx.fillStyle='#182032cc';ctx.fillRect(w.x-48,w.y-67,96,10);ctx.fillStyle='#ffbe4d';ctx.fillRect(w.x-46,w.y-65,92*p,6);text(`СИЛА ${Math.round(p*100)}%`,w.x,w.y-75,11);}if(w.weapon==='wall')drawWallPreview();}} [projectile,...airBombs].filter(Boolean).forEach(p=>{ctx.fillStyle='#fff5a3';ctx.beginPath();ctx.arc(p.x,p.y,6,0,7);ctx.fill();ctx.fillStyle='#f05e45';ctx.beginPath();ctx.arc(p.x,p.y,3,0,7);ctx.fill();}); particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);});ctx.globalAlpha=1; explosions.forEach(drawExplosion);drawWeaponBar();if(weaponMenu)drawWeaponMenu();
    const w=activeWorm(), remain=Math.max(0,30-(performance.now()-turnStart)/1000);if(!gameOver&&w){const tm=teams[w.team];ctx.fillStyle='#152137b5';ctx.fillRect(W/2-135,17,270,40);text(`${tm.name}: ход ${Math.ceil(remain)} сек.`,W/2,44,17,tm.color);document.querySelector('#turnInfo').innerHTML=`<b style="color:${tm.color}">${tm.name} — ход</b>`;} if(gameOver){const winner=worms.some(w=>w.alive&&w.team===0)?teams[0]:teams[1],menu=document.querySelector('#gameOverMenu');document.querySelector('#gameOverTitle').textContent=`ПОБЕДА: ${winner.name.toUpperCase()}!`;document.querySelector('#gameOverNote').textContent=isHost?'Начать матч тем же составом':'Ожидаем, пока ведущий начнёт матч заново';document.querySelector('#playAgain').style.display=isHost?'inline-block':'none';menu.style.display='grid';document.querySelector('#turnInfo').innerHTML='<b>Матч окончен</b>';}}
  function loop(now){const dt=Math.min(.03,(now-last)/1000||0);last=now;explosions.forEach(e=>e.age+=dt);explosions=explosions.filter(e=>e.age<e.max);update(dt);draw();requestAnimationFrame(loop);} 
  window.addEventListener('keydown',e=>{if(['Space','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(!ownsTurn())return;const map={Digit1:'bazooka',Digit2:'airstrike',Digit3:'wall',Digit4:'goatdrop',Digit5:'minedrop',Digit6:'reinforce'};if(map[e.code]){if(isHost){activeWorm().weapon=map[e.code];weapon=map[e.code];}else sendCommand('weapon',{weapon:map[e.code]});return;}if(isHost)keys[e.code]=true;else if(['KeyA','KeyD','ArrowLeft','ArrowRight','Space'].includes(e.code))lobbyRef.child(`input/${selectedPlayer}/${e.code}`).set(true);});
  window.addEventListener('keyup',e=>{if(isHost)keys[e.code]=false;else if(gameStarted&&selectedPlayer&&['KeyA','KeyD','ArrowLeft','ArrowRight','Space'].includes(e.code))lobbyRef.child(`input/${selectedPlayer}/${e.code}`).set(false);});
  canvas.addEventListener('mousemove',e=>{let b=canvas.getBoundingClientRect(),nextMouse={x:(e.clientX-b.left)*W/b.width,y:(e.clientY-b.top)*H/b.height};if(!gameStarted||!isHost||ownsTurn())mouse=nextMouse;if(gameStarted&&!isHost&&ownsTurn()&&performance.now()-lastAimPublish>45){lastAimPublish=performance.now();sendCommand('aim',nextMouse);}});
  canvas.addEventListener('contextmenu',e=>{e.preventDefault();weaponMenu=false;});
  canvas.addEventListener('mousedown',e=>{if(e.button!==0||!ownsTurn()||projectile||gameOver)return;if(activeWorm().weapon==='bazooka'){charging=true;chargeStart=performance.now();}else if(isHost)fire(1);else sendCommand('fire',{power:1,mouse:{x:mouse.x,y:mouse.y}});});
  window.addEventListener('mouseup',e=>{if(e.button===0&&charging){let power=Math.min(1,(performance.now()-chargeStart)/1300);charging=false;if(isHost)fire(power);else sendCommand('fire',{power,mouse:{x:mouse.x,y:mouse.y}});}});
  document.querySelector('#playAgain').addEventListener('click',()=>{if(isHost){reset();publishState(true);publishTerrain();}});
  function setupLobby(){
    const startMenu=document.querySelector('#startMenu'),lobby=document.querySelector('#lobby'),status=document.querySelector('#lobbyStatus'),clientId=sessionStorage.getItem('worms-client')||crypto.randomUUID();
    let players={},match=null,joining=false,opponentWasHere=false,departureNotified=false;
    sessionStorage.setItem('worms-client',clientId);
    function startSolo(){
      botMode=true;selectedPlayer='1';isHost=true;gameStarted=true;startMenu.style.display='none';reset();
    }
    function openMultiplayer(){
      botMode=false;startMenu.style.display='none';lobby.style.display='grid';
      firebase.initializeApp(firebaseConfig);
      // One public queue: the first two browsers automatically receive a team.
      lobbyRef=firebase.database().ref('worms-quick-match');
      bindMultiplayer();
      join(1);
    }
    addEventListener('pagehide',()=>{if(lobbyRef&&selectedPlayer)lobbyRef.child(`players/${selectedPlayer}`).remove();},{once:true});
    function hasBothPlayers(){return players['1']&&players['2'];}
    function matchIsCurrent(){return match?.started&&hasBothPlayers()&&match.hostClientId===players['1'].clientId&&match.guestClientId===players['2'].clientId;}
    function beginIfReady(){
      if(!matchIsCurrent()||gameStarted||!selectedPlayer)return;
      isHost=selectedPlayer==='1';gameStarted=true;lobby.style.display='none';
      if(isHost)reset();bindNetwork();
    }
    function createMatch(){
      if(selectedPlayer!=='1'||!hasBothPlayers()||gameStarted)return;
      const hostClientId=players['1'].clientId,guestClientId=players['2'].clientId;
      lobbyRef.child('match').transaction(current=>current?.hostClientId===hostClientId&&current?.guestClientId===guestClientId?current:{started:firebase.database.ServerValue.TIMESTAMP,hostClientId,guestClientId}).then(result=>{
        const created=result.snapshot.val();
        if(result.committed&&created?.hostClientId===hostClientId&&created?.guestClientId===guestClientId){lobbyRef.child('commands').remove();lobbyRef.child('input').remove();}
      });
    }
    function updateLobby(){
      const opponent=selectedPlayer==='1'?'2':'1';
      if(players[opponent])opponentWasHere=true;
      if(gameStarted&&opponentWasHere&&!players[opponent]&&!departureNotified){departureNotified=true;const notice=document.querySelector('#connectionNotice');notice.textContent='Соперник отключился от матча';notice.style.display='block';}
      if(gameStarted)return;
      if(!selectedPlayer){status.textContent='Игра уже занята. Подождите, пока освободится место.';return;}
      if(!hasBothPlayers()){status.textContent=`Вы ${selectedPlayer==='1'?'в красной':'в синей'} команде — ждём второго игрока…`;return;}
      status.textContent='Соперник найден — начинаем!';createMatch();beginIfReady();
    }
    function join(slot){
      if(joining||selectedPlayer)return;joining=true;
      const playerRef=lobbyRef.child(`players/${slot}`);
      playerRef.transaction(current=>current&&current.clientId!==clientId?undefined:{clientId,joinedAt:firebase.database.ServerValue.TIMESTAMP}).then(result=>{
        joining=false;
        if(result.committed){selectedPlayer=String(slot);playerRef.onDisconnect().remove();updateLobby();}
        else if(slot===1)join(2);else updateLobby();
      });
    }
    document.querySelector('#solo').addEventListener('click',startSolo);
    document.querySelector('#multiplayer').addEventListener('click',openMultiplayer);
    function bindMultiplayer(){
      lobbyRef.child('players').on('value',snap=>{players=snap.val()||{};updateLobby();});
      lobbyRef.child('match').on('value',snap=>{match=snap.val();beginIfReady();});
    }
  }
  reset();setupLobby();requestAnimationFrame(loop);
})();
